/* Main.c file generated by New Project wizard
 *
 * Created:   mar. déc. 22 2020
 * Processor: PIC16F887
 * Compiler:  MPLAB XC8
 */

// PIC16F887 Configuration Bit Settings

// 'C' source line config statements

// CONFIG1
#pragma config FOSC = HS        // Oscillator Selection bits (HS oscillator: High-speed crystal/resonator on RA6/OSC2/CLKOUT and RA7/OSC1/CLKIN)
#pragma config WDTE = OFF       // Watchdog Timer Enable bit (WDT disabled and can be enabled by SWDTEN bit of the WDTCON register)
#pragma config PWRTE = OFF      // Power-up Timer Enable bit (PWRT disabled)
#pragma config MCLRE = OFF      // RE3/MCLR pin function select bit (RE3/MCLR pin function is digital input, MCLR internally tied to VDD)
#pragma config CP = OFF         // Code Protection bit (Program memory code protection is disabled)
#pragma config CPD = OFF        // Data Code Protection bit (Data memory code protection is disabled)
#pragma config BOREN = ON       // Brown Out Reset Selection bits (BOR enabled)
#pragma config IESO = ON        // Internal External Switchover bit (Internal/External Switchover mode is enabled)
#pragma config FCMEN = ON       // Fail-Safe Clock Monitor Enabled bit (Fail-Safe Clock Monitor is enabled)
#pragma config LVP = ON         // Low Voltage Programming Enable bit (RB3/PGM pin has PGM function, low voltage programming enabled)

// CONFIG2
#pragma config BOR4V = BOR40V   // Brown-out Reset Selection bit (Brown-out Reset set to 4.0V)
#pragma config WRT = OFF        // Flash Program Memory Self Write Enable bits (Write protection off)

// #pragma config statements should precede project file includes.
// Use project enums instead of #define for ON and OFF.
#define A1 RB0
#define A2 RB1
#define A3 RB2
#define A4 RB3
#define B1 RB4
#define B2 RB5
#define B3 RB6
#define B4 RB7
#define LA1 RD0
#define LA2 RD1
#define LA3 RD2
#define LA4 RD3
#define LB1 RD4
#define LB2 RD5
#define LB3 RD6
#define LB4 RD7


#define _XTAL_FREQ  20e6
#include <string.h>
#include <xc.h>
int phase;
char t;
int etape = 0;
// Fréquence de transmission 9600 Baud
//Mode 8bits

void uart_unit(void) {
    TXEN = 1;
    SYNC = 0;
    BRGH = 1;
    BRG16 = 0;
    SPBRG = 129;
    SPEN = 1;
    CREN = 1; //activation de la reception de données
    GIE = 1; //interruption globale 
    PEIE = 1; //interruprion des périphiques 
    INTE = 1;
    RCIE = 1; //interruption pour la recption de données
    RBIE = 1;
    IOCB = 0xFF; //Activation des interruptions sur les ports B
}

void uart_txChar(unsigned char ch) {
    while (!TRMT);
    TXREG = ch;
}

void uart_txStr(unsigned const char *str) {
    while (*str != '\0') {
        uart_txChar(*str);
        str++;
    }
    uart_txChar('\r');
    uart_txChar('\n');
}

void interrupt jdk1() {
    if (RCIF) {
        RCIF = 0;
        if (RCREG == 'I' || ((LA1 == 1 || LA2 == 1 || LA3 == 1 || LA4 == 1 || LB1 == 1 || LB2 == 1 || LB3 == 1 || LB4 == 1) && RCREG == 'V')) {
            LA1 = 0;
            LA2 = 0;
            LA3 = 0;
            LA4 = 0;
            LB1 = 0;
            LB2 = 0;
            LB3 = 0;
            LB4 = 0;
            phase = 0;
        }
        if (RCREG == 'Q') {
            LA1 = 1;
            LA2 = 1;
            LA3 = 1;
            LA4 = 1;
            LB1 = 1;
            LB2 = 1;
            LB3 = 1;
            LB4 = 1;
            phase = 3;
        }
        if (RCREG == '1') {
            etape = 1; //Etape 1 du je Vrai ou Faux
        } else if (RCREG == '2') {
            etape = 2; //Etape 
        } else if (RCREG == '3') {
            etape = 3; //Etape 1 du je Vrai ou Faux
        }
        if (RCREG == 'B') {
            LA1 = 0;
            LA2 = 0;
            LA3 = 0;
            LA4 = 0;
            phase = 1;
        }
        if (RCREG == 'A') {
            LB1 = 0;
            LB2 = 0;
            LB3 = 0;
            LB4 = 0;
            phase = 2;
        }

    }


    //Envoi des données au logiciel 
    if (RBIF) {
        RBIF = 0;
        //Etape 1
        while (etape == 1) {
            while (A1 == 0 && (phase == 0 || phase == 2)) {
                LA1 = 1;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe A a la main");
                __delay_ms(3000);
                LA1 = 0;
                phase = 3;
                __delay_ms(4000);
                if (RCREG == 'I') {
                    phase = 0;
                } else {
                    phase = 3;
                    uart_txStr("L'Equipe B a la main");
                }
            }
            while (A2 == 0 && (phase == 0 || phase == 2)) {
                LA2 = 1;
                LA1 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe A a la main");
                __delay_ms(3000);
                LA2 = 0;
                phase = 3;
                __delay_ms(4000);
                if (RCREG == 'I') {
                    phase = 0;
                } else {
                    phase = 3;
                    uart_txStr("L'Equipe B a la main");
                }
            }
            while (A3 == 0 && (phase == 0 || phase == 2)) {
                LA3 = 1;
                LA1 = 0;
                LA2 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe A a la main");
                __delay_ms(3000);
                LA3 = 0;
                phase = 3;
                __delay_ms(4000);
                if (RCREG == 'I') {
                    phase = 0;
                } else {
                    phase = 3;
                    uart_txStr("L'Equipe B a la main");
                }
            }
            while (A4 == 0 && (phase == 0 || phase == 2)) {
                LA4 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe A a la main");
                __delay_ms(3000);
                LA4 = 0;
                phase = 3;
                __delay_ms(4000);
                if (RCREG == 'I') {
                    phase = 0;
                } else {
                    phase = 3;
                    uart_txStr("L'Equipe B a la main");
                }
            }
            while (B1 == 0 && (phase == 0 || phase == 1)) {
                LB1 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe B a la main");
                __delay_ms(3000);
                LB1 = 0;
                phase = 3;
                __delay_ms(4000);
                if (RCREG == 'I') {
                    phase = 0;
                } else {
                    phase = 3;
                    uart_txStr("L'Equipe A a la main");
                }
            }
            while (B2 == 0 && (phase == 0 || phase == 1)) {
                LB2 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe B a la main");
                __delay_ms(3000);
                LB2 = 0;
                phase = 3;
                __delay_ms(4000);
                if (RCREG == 'I') {
                    phase = 0;
                } else {
                    phase = 3;
                    uart_txStr("L'Equipe A a la main");
                }
            }
            while (B3 == 0 && (phase == 0 || phase == 1)) {
                LB3 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe B a la main");
                __delay_ms(3000);
                LB3 = 0;
                phase = 3;
                __delay_ms(4000);
                if (RCREG == 'I') {
                    phase = 0;
                } else {
                    phase = 3;
                    uart_txStr("L'Equipe A a la main");
                }
            }
            while (B4 == 0 && (phase == 0 || phase == 1)) {
                LB4 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                uart_txStr("L'Equipe B a la main");
                __delay_ms(3000);
                LB4 = 0;
                phase = 3;
                __delay_ms(4000);
                if (RCREG == 'I') {
                    phase = 0;
                } else {
                    phase = 3;
                    uart_txStr("L'Equipe A a la main");
                }
            }
            //Etape 2
        }
        while (etape == 2) {
            if (A1 == 0 && (phase == 0 || phase == 2)) {
                LA1 = 1;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe A a la main");
                __delay_ms(6000);
                LA1 = 0;
            } else if (A2 == 0 && (phase == 0 || phase == 2)) {
                LA2 = 1;
                LA1 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe A a la main");
                __delay_ms(6000);
                LA2 = 0;
            } else if (A3 == 0 && (phase == 0 || phase == 2)) {
                LA3 = 1;
                LA1 = 0;
                LA2 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe A a la main");
                __delay_ms(6000);
                LA3 = 0;

            } else if (A4 == 0 && (phase == 0 || phase == 2)) {
                LA4 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe A a la main");
                __delay_ms(6000);
                LA4 = 0;
            } else if (B1 == 0 && (phase == 0 || phase == 1)) {
                LB1 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe B a la main");
                __delay_ms(6000);
                LB1 = 0;
            } else if (B2 == 0 && (phase == 0 || phase == 1)) {
                LB2 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe B a la main");
                __delay_ms(6000);
                LB2 = 0;
            } else if (B3 == 0 && (phase == 0 || phase == 1)) {
                LB3 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe B a la main");
                __delay_ms(6000);
                LB3 = 0;

            } else if (B4 == 0 && (phase == 0 || phase == 1)) {
                LB4 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                uart_txStr("L'Equipe B a la main");
                __delay_ms(6000);
                LB4 = 0;
            }
        }
        //Etape 3
        while (etape == 3) {
            if (A1 == 0 && phase == 2) {
                LA1 = 1;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe A a la main");
                __delay_ms(6000);
                LA1 = 0;
                phase = 3;
                __delay_ms(4000);
                if (RCREG == 'I') {
                    phase = 0;
                }

                if (B1 == 0) {
                    LB1 = 1;
                    LB2 = 0;
                    LB3 = 0;
                    LB4 = 0;
                    uart_txStr("L'Equipe B a la main");
                    __delay_ms(6000);
                    LB1 = 0;
                    phase = 3;
                }

            } else if (A2 == 0 && phase == 2) {
                LA2 = 1;
                LA1 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe A a la main");
                __delay_ms(6000);
                LA2 = 0;
            } else if (A3 == 0 && phase == 2) {
                LA3 = 1;
                LA1 = 0;
                LA2 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe A a la main");
                __delay_ms(6000);
                LA3 = 0;

            } else if (A4 == 0 && phase == 2) {
                LA4 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe A a la main");
                __delay_ms(6000);
                LA4 = 0;
            } else if (B1 == 0 && phase == 1) {
                LB1 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB2 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe B a la main");
                __delay_ms(6000);
                LB1 = 0;
            } else if (B2 == 0 && 0 || phase == 1) {
                LB2 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB3 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe B a la main");
                __delay_ms(6000);
                LB2 = 0;
            } else if (B3 == 0 && phase == 1) {
                LB3 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB4 = 0;
                uart_txStr("L'Equipe B a la main");
                __delay_ms(6000);
                LB3 = 0;

            } else if (B4 == 0 && phase == 1) {
                LB4 = 1;
                LA1 = 0;
                LA2 = 0;
                LA3 = 0;
                LA4 = 0;
                LB1 = 0;
                LB2 = 0;
                LB3 = 0;
                uart_txStr("L'Equipe B a la main");
                __delay_ms(6000);
                LB4 = 0;
            }
        }
    }

}

void main(void) {
    ANSEL = 0;
    ANSELH = 0;
    TRISD0 = 0;
    TRISD1 = 0;
    TRISD2 = 0;
    TRISD3 = 0;
    TRISD4 = 0;
    TRISD5 = 0;
    TRISD6 = 0;
    TRISD7 = 0;
    RD0 = 0;
    RD1 = 0;
    RD2 = 0;
    RD3 = 0;
    RD4 = 0;
    RD5 = 0;
    RD6 = 0;
    RD7 = 0;
    uart_unit();
    while (1);
}